id: opecha:P000736
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19893
  title: 'སྟོབས་དང་དཔའ་རྩལ་འགྲན་ཟླ་མེད་པ་གྲུབ་པའི་དབང་ཕྱུག་འཁོར་ལོས་བསྒྱུར་བའི་རྒྱལ་པོ་མི་རྗེ་འཛམ་གླིང་སེང་ཆེན་ནོར་བུ་དགྲ་འདུལ་གྱི་ངེས་བརྗོད་ཐེ་ཚོམ་དྲྭ་བ་གཅོད་པའི་རལ་གྲི། '
  volume: ''
  author: ''
