id: I087C36A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:27:09+00:00'
last_modified: '2022-06-07T13:35:57.030105+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19893
  title: 'སྟོབས་དང་དཔའ་རྩལ་འགྲན་ཟླ་མེད་པ་གྲུབ་པའི་དབང་ཕྱུག་འཁོར་ལོས་བསྒྱུར་བའི་རྒྱལ་པོ་མི་རྗེ་འཛམ་གླིང་སེང་ཆེན་ནོར་བུ་དགྲ་འདུལ་གྱི་ངེས་བརྗོད་ཐེ་ཚོམ་དྲྭ་བ་གཅོད་པའི་རལ་གྲི། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B3F5:
      image_group_id: I2PD20543
      title: ''
      total_pages: 120
      order: 1
      base_file: B3F5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
